columns:
  - case_id: category
  - continent: category
  - education_of_employee: category
  - has_job_experience: category
  - requires_job_training: category
  - no_of_employees: int
  - yr_of_estab: int
  - region_of_employment: category
  - prevailing_wage: float
  - unit_of_wage: category
  - full_time_position: category
  - case_status: category

numerical_columns:
  - no_of_employees
  - yr_of_estab
  - prevailing_wage

categorical_columns:
  - case_id
  - continent
  - education_of_employee
  - has_job_experience
  - requires_job_training
  - region_of_employment
  - unit_of_wage
  - full_time_position
  - case_status


# data preprocessing
drop_columns:
  - case_id

target_column: case_status


transform_features:
  - company_age
  - no_of_employees

num_features:
  - prevailing_wage

one_hot_encoding_columns:
  - has_job_experience
  - requires_job_training
  - full_time_position
  - education_of_employee

Ordinal_encoding_columns:
  - continent
  - unit_of_wage
  - region_of_employment
