name: DVC Pipeline Automation

on:
  push:
    branches:
      - ops
  pull_request:
    branches:
      - main  

jobs:
  lint-and-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Lint the code
        run: flake8 src/

      - name: Run data injection script
        env:
          MONGO_URI: ${{ secrets.MONGO_CONNECTION_URL }}
        run: python src/data/data_injection.py

      - name: Run data validation script
        env:
          MONGO_URI: ${{ secrets.MONGO_CONNECTION_URL }}
        run: python src/data/data_validation.py

      - name: Run data preprocessing script
        run: python src/data/data_preprocessing.py