name: DVC Pipeline Automation

on:
  push:
    branches:
      - ops
  pull_request:
    branches:
      - main

jobs:
  code-linting:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
         pip install -r requirements.txt

    - name: Linting the code 
      run: |
        flake8 src/
  code checking:
    - name: Run data injection script
      env:
          MONGO_URI: ${{ secrets.MONGO_URI }}
      run: python src/data/data_injection.py







